fjerner_pre_commit_hooks (#27)

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,9 +1,9 @@
 #!/bin/sh
 
-isMaster=$(git branch | grep \* | sed 's/* master$/1/g')
+#isMaster=$(git branch | grep \* | sed 's/* master$/1/g')
 
-error_msg="Avbryter commit. Det er ikke tillat å committe til master."
+#error_msg="Avbryter commit. Det er ikke tillat å committe til master."
 
-if [[ "$isMaster" = "1" ]]; then
-    echo "$error_msg" >&2
-fi
+#if [[ "$isMaster" = "1" ]]; then
+#    echo "$error_msg" >&2
+#fi
